language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'



script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r aws-springboot *
  - mkdir -p deploy
  - mv aws-springboot.zip deploy/aws-springboot.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY

    secret_access_key: $AWS_SECRET_KEY

    bucket: aws-springboot-build-cholongbul
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    loclal_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY

    secret_access_key: $AWS_SECRET_KEY

    bucket: aws-springboot-build-cholongbul
    key: aws-springboot.zip
    bundle_type: zip
    application: aws-springboot
    deployment_group: aws-springboot-group

    region: ap-northeast-2
    wait-until-deployed: true


# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - meyoub612@naver.com



